services:
  - type: web
    name: inventory-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: inventory-backend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: inventory-db
          property: connectionString
      - key: JWT_ACCESS_TOKEN_LIFETIME
        value: 60
      - key: JWT_REFRESH_TOKEN_LIFETIME
        value: 1440
      - key: CORS_ALLOWED_ORIGINS
        value: https://inventory-frontend.vercel.app

databases:
  - name: inventory-db
    databaseName: inventory_db
    user: inventory_user
    plan: free 